import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { performance } from 'node:perf_hooks'
import { OfflineGraph } from '../packages/graph/src/graph/offline.js'
import { readSnapshot } from '../packages/graph/src/ingest/snapshot.js'
import { getExposureReport } from '../packages/graph/src/runtime.js'
import { scanResolvedPackages } from '../packages/graph/src/runtime.js'
import { readLockfile } from '../packages/graph/src/lockfile/parse.js'
import type { FixturePackage } from '../packages/graph/src/types/index.js'

const root = fileURLToPath(new URL('..', import.meta.url))
const fixturePath = resolve(root, 'packages/graph/fixtures/packages.jsonl')
const demoLockfilePath = resolve(root, 'packages/graph/fixtures/demo-lockfile.json')
const landingDataPath = resolve(root, 'packages/landing/src/data/demo-fixtures.ts')
const layoutPath = resolve(root, 'packages/landing/src/canvas/layout.ts')
const metricsPath = resolve(root, 'packages/graph/fixtures/build-metrics.json')

const popularNames = ['left-pad', 'leftpadd', 'leftpad', 'express', 'react', 'lodash', 'axios', 'fastify', 'vite', 'webpack', 'typescript', 'commander', 'zod', 'chalk', 'debug', 'glob', 'semver', 'kleur', 'undici', 'minimist', 'rimraf', 'ora', 'esbuild', 'shared-core', 'demo-service']
const totalPackages = 1500
const affectedPackageCount = 42
const epoch = Date.UTC(2024, 0, 1)

function digestFor(name: string, version: string): string {
  let hash = 2166136261
  for (const character of `${name}@${version}`) {
    hash ^= character.charCodeAt(0)
    hash = Math.imul(hash, 16777619)
  }
  return `sha256-${(hash >>> 0).toString(16).padStart(8, '0')}`
}

function packageName(index: number): string {
  return popularNames[index] ?? `pkg-${String(index - popularNames.length + 1).padStart(4, '0')}`
}

function makeDependencies(index: number, name: string): Record<string, string> {
  if (name === 'left-pad') return {}
  if (index > 0 && index <= affectedPackageCount) {
    const dependencyName = index > 1 ? packageName(index - 1) : 'shared-core'
    return { 'left-pad': '1.0.0', [dependencyName]: '1.0.0' }
  }
  if (index === affectedPackageCount + 1) return {}
  if (index > affectedPackageCount) {
    const dependencyName = packageName(index - 1)
    return { [dependencyName]: '1.0.0' }
  }
  return { 'shared-core': '1.0.0' }
}

function makePackage(index: number): FixturePackage {
  const name = packageName(index)
  const firstVersion = { version: '1.0.0', publishedAt: epoch + index * 86400000, digest: digestFor(name, '1.0.0'), dependencies: makeDependencies(index, name) }
  const secondVersion = { version: '1.1.0', publishedAt: epoch + (index + totalPackages) * 86400000, digest: digestFor(name, '1.1.0'), dependencies: makeDependencies(index, name) }
  const maintainer = index % 9 === 0 ? 'hydra-labs' : `maintainer-${index % 31}`
  const services = [{ name: `service:${name}`, source: 'fixture', version: `${name}@1.1.0` }]
  if (name === 'left-pad') services.push({ name: 'demo-app', source: 'demo-lockfile', version: 'left-pad@1.0.0' })
  return { package: { name, downloads: 1000 + (totalPackages - index) * 17, createdAt: epoch - index * 3600000 }, versions: [firstVersion, secondVersion], maintainers: [maintainer], services }
}

function layoutFor(rows: FixturePackage[]): string {
  const nodes = rows.flatMap((row) => row.versions.map((version) => `${row.package.name}@${version.version}`))
  const points = nodes.map((id, index) => {
    const angle = index * 2.399963229728653
    const radius = 0.13 + (index % 97) / 110
    return { id, x: Math.round((0.5 + Math.cos(angle) * radius * 0.46) * 10000) / 10000, y: Math.round((0.5 + Math.sin(angle) * radius * 0.46) * 10000) / 10000 }
  })
  const edges = rows.flatMap((row) => row.versions.flatMap((version) => Object.entries(version.dependencies).map(([name, dependencyVersion]) => ({ from: `${row.package.name}@${version.version}`, to: `${name}@${dependencyVersion}` }))))
  return `// generated by scripts/generate-fixtures.ts\nexport interface LayoutPoint { id: string, x: number, y: number }\nexport interface LayoutEdge { from: string, to: string }\nexport const layoutPoints: LayoutPoint[] = ${JSON.stringify(points)}\nexport const layoutEdges: LayoutEdge[] = ${JSON.stringify(edges)}\n`
}

async function main(): Promise<void> {
  const rows = Array.from({ length: totalPackages }, (_, index) => makePackage(index))
  await mkdir(dirname(fixturePath), { recursive: true })
  await mkdir(dirname(landingDataPath), { recursive: true })
  await writeFile(fixturePath, `${rows.map((row) => JSON.stringify(row)).join('\n')}\n`, 'utf8')
  const lockfile = { name: 'aftershock-demo', lockfileVersion: 3, requires: true, packages: {
    '': { name: 'aftershock-demo', version: '1.0.0', dependencies: { 'demo-service': '1.0.0' } },
    'node_modules/demo-service': { version: '1.0.0', resolved: 'fixture:demo-service', dependencies: { 'left-pad': '1.0.0' } },
    'node_modules/left-pad': { version: '1.0.0', resolved: 'fixture:left-pad' },
  } }
  await writeFile(demoLockfilePath, `${JSON.stringify(lockfile, null, 2)}\n`, 'utf8')
  await writeFile(layoutPath, layoutFor(rows), 'utf8')
  const graph = new OfflineGraph(rows)
  const runtime = { mode: 'offline' as const, offline: graph }
  const closureStartedAt = performance.now()
  const report = await getExposureReport(runtime, 'left-pad')
  const closureMs = Math.max(0.01, Math.round((performance.now() - closureStartedAt) * 100) / 100)
  const scanStartedAt = performance.now()
  await scanResolvedPackages(runtime, await readLockfile(demoLockfilePath))
  const scanMs = Math.max(0.01, Math.round((performance.now() - scanStartedAt) * 100) / 100)
  const counts = graph.counts()
  let persistedMetrics: { closureMs?: number, scanMs?: number } | undefined
  try { persistedMetrics = JSON.parse(await readFile(metricsPath, 'utf8')) as { closureMs?: number, scanMs?: number } } catch { persistedMetrics = undefined }
  const fixtureMetrics = { ...counts, closureMs: persistedMetrics?.closureMs ?? closureMs, scanMs: persistedMetrics?.scanMs ?? scanMs }
  const demoData = `// generated from the deterministic fixture and offline query measurements\nimport type { ExposureReport, LockfileFinding } from '@aftershock/graph/types'\n\nexport const demoReport: ExposureReport = ${JSON.stringify(report, null, 2)}\nexport const demoFinding: LockfileFinding = ${JSON.stringify({ resolved: 'left-pad@1.0.0', path: ['root', 'demo-service@1.0.0', 'left-pad@1.0.0'], reaches: true, firstBadWindowOverlap: true }, null, 2)}\nexport const fixtureCounts = ${JSON.stringify(counts)}\nexport const fixtureMetrics = ${JSON.stringify(fixtureMetrics)}\nexport const fixtureStory = { artifacts: ${affectedPackageCount * 2}, packages: ${affectedPackageCount}, minutes: 6 }\n`
  await writeFile(landingDataPath, demoData, 'utf8')
  await writeFile(resolve(root, 'packages/graph/fixtures/fixture-manifest.json'), `${JSON.stringify({ packageCount: totalPackages, versionCount: totalPackages * 2, affectedPackageCount, artifactCount: affectedPackageCount * 2 }, null, 2)}\n`, 'utf8')
  process.stdout.write(`generated ${totalPackages} packages, ${totalPackages * 2} versions, ${affectedPackageCount} affected packages\n`)
}

await main()
