import { FadeIn } from '../ui/FadeIn'
import { AttackMap } from '../../canvas/AttackMap'
import { demoReport, fixtureCounts } from '../../data/demo-fixtures'

/** Renders one live evidence cell for each of the five graph questions. */
export function QuestionsBento() {
  return <section className="bg-[var(--bg-primary)] px-4 py-[8rem]"><div className="mx-auto max-w-6xl"><FadeIn><h2 className="max-w-xl font-display text-[2.5rem] font-bold leading-[1.1] tracking-[-0.01em] text-[var(--text-primary)] md:text-[3rem]">the five questions a breach actually asks</h2></FadeIn><div className="mt-12 grid grid-cols-1 gap-px overflow-hidden rounded-[8px] border border-[var(--border-default)] bg-[var(--border-default)] md:grid-cols-12"><FadeIn delay={0}><div className="min-h-[360px] bg-[var(--bg-surface)] p-6 md:col-span-7 md:row-span-2"><div className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--text-muted)]">question 01</div><h3 className="mt-4 font-sans text-xl font-medium leading-[1.3] text-[var(--text-primary)]">which services are transitively exposed</h3><p className="mt-3 font-sans text-sm font-light leading-[1.6] text-[var(--text-secondary)]">a reverse depends_on closure over the versioned graph, depth and elapsed time on every node</p><div className="mt-6 h-[180px] overflow-hidden rounded-[4px] border border-[var(--border-subtle)]"><AttackMap events={demoReport.events} mini /></div></div></FadeIn><EvidenceCell delay={0.08} label="question 02" heading="which version introduced it" answer={`first seen in ${demoReport.comprom.version}, publishedAt ordering across the flagged set`} /><EvidenceCell delay={0.16} label="question 03" heading="which apps resolved it while it was live" answer={`resolves edges joined against the publish window, ${demoReport.totalExposed} paths attached`} /><EvidenceCell delay={0.24} label="question 04" heading="what else does this maintainer touch" answer={`${demoReport.maintainerNeighbourhood.length} neighbouring packages on the maintains traversal`} /><EvidenceCell delay={0.32} label="question 05" heading="which names sit close enough to trick you" answer={`${demoReport.typosquats.length} similar_name edges ranked by distance`} /><FadeIn delay={0.4}><div className="bg-[var(--bg-elevated)] p-6 md:col-span-4"><p className="font-sans text-sm font-light leading-[1.6] text-[var(--text-secondary)]">every answer is one query</p><a href="https://github.com/dr4ken-soul/Aftershock/blob/main/packages/graph/src/graph/queries.ts" className="mt-6 inline-flex rounded-[4px] border border-[var(--border-default)] px-4 py-2 font-sans text-sm font-medium text-[var(--text-primary)] transition-colors duration-200 hover:border-[var(--accent)] hover:text-[var(--accent)]">read the queries</a><p className="mt-8 font-mono text-xs uppercase tracking-[0.15em] text-[var(--text-muted)]">{fixtureCounts.packageNodes} package nodes in the fixture</p></div></FadeIn></div></div></section>
}

function EvidenceCell({ label, heading, answer, delay }: { label: string, heading: string, answer: string, delay: number }) {
  return <FadeIn delay={delay}><div className="cell-hover bg-[var(--bg-surface)] p-6 md:col-span-5"><div className="font-mono text-xs uppercase tracking-[0.15em] text-[var(--text-muted)]">{label}</div><h3 className="mt-4 font-sans text-xl font-medium leading-[1.3] text-[var(--text-primary)]">{heading}</h3><p className="mt-4 font-mono text-sm leading-7 text-[var(--accent)]">{answer}</p></div></FadeIn>
}
